### PR TITLE
feat: multilingualization of context menu

### PR DESCRIPTION
**Pull request by kiibo382**
## Objectives
  - related issue: #27

## Implementation
  - Using vue-i18n, the contextmenu can be displayed in English.
  - You can switch the language by passing the locale to this module in props.

### CODE REVIEW

**Comment by hellowuxin** [comment]
well done, but vue-i18n is not tailored for use in component libraries, so maybe try another way.

**Comment by kiibo382** [comment]
@hellowuxin 
> well done, but vue-i18n is not tailored for use in component libraries, so maybe try another way.

Why is vue-i18n not suitable for component libraries? Please explain in detail.

Do you want to apply i18n resources asynchronously with lazy load?
If so, I will try to support lazy load by referring to the following.
https://github.com/intlify/vue-i18n-next/tree/master/examples/lazy-loading

**Comment by hellowuxin** [comment]
> @hellowuxin
> 
> > well done, but vue-i18n is not tailored for use in component libraries, so maybe try another way.
> 
> Why is vue-i18n not suitable for component libraries? Please explain in detail.
> 
> Do you want to apply i18n resources asynchronously with lazy load? If so, I will try to support lazy load by referring to the following. https://github.com/intlify/vue-i18n-next/tree/master/examples/lazy-loading

see https://github.com/kazupon/vue-i18n/issues/746

**Comment by hellowuxin** [comment]
use i18n instead

**Comment by kiibo382** [comment]
thanks!

**Pull request closed without merging**
